openapi: 3.0.0
info:
  title: Todo APP
  description: API to manage todos
  version: "1.0.0"
servers:
  - url: http://localhost:3000
paths:
  /signup:
    post:
      summary: Let the User SignUp
      description: Endpoint to register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpSchema'
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SignUpSchema'
components:
  schemas:
    SignUpSchema:
      type: object
      properties:
        email:
          type: string
          description: The email address of the subscriber.
        password:
          type: string
          description: The password of the subscriber.
      required:
        - email
        - password
    SignUpResponse:
      type: object
      properties:
        message:
          type: string
          description: The message of error or success for user.
      required:
        - message